eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.4:8010/eureka/
server:
  port: 8383
---
spring:
  profiles: dev
  application:
    name: customer

---
spring:
  profiles:
    active: dev