---
# This default profile is used when running a single instance completely standalone:
spring:
  application:
    # sets the name in Eureka
    name: ${springboot.app.name:eureka-serviceregistry}

server:
  port: 8010

eureka:
  instance:
    hostname: ${springboot.app.name:eureka-serviceregistry}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/